name: Test build

on:
  push:
  pull_request:

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Ensure build was committed (necessary for Github Actions)
        run: |
          if [[ -n $(git status -s dist) ]]; then
            echo "Uncommitted changes found in dist directory."
            exit 1
          else
            echo "No uncommitted changes in dist directory."
          fi

      - name: "[Test] Unit tests"
        run: yarn test
